import { enUS } from "./locales/en-US";

export const zhCN = {
  "common.add": "添加",
  "common.open": "打开",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.confirmYes": "是",
  "common.confirmNo": "否",
  "common.save": "保存",
  "common.saving": "保存中",
  "common.delete": "删除",
  "common.retry": "重试",
  "common.done": "完成",
  "common.refresh": "刷新",
  "common.refreshing": "刷新中",
  "common.restoreDefault": "恢复默认",
  "common.view": "查看",
  "common.collapse": "收起",
  "common.start": "启动",
  "common.starting": "启动中",
  "common.stop": "停止",
  "common.running": "运行中",
  "common.stopped": "已停止",
  "common.available": "可用",
  "common.unavailable": "暂不可用",
  "common.unselected": "未选择",
  "common.notDetected": "未检测到",
  "common.notCreated": "尚未创建",
  "common.idle": "空闲",
  "common.loading": "加载中",
  "common.loaded": "已加载",
  "common.loadFailed": "加载失败",
  "common.completed": "已完成",
  "common.cancelled": "已取消",
  "common.failed": "失败",
  "common.abnormal": "异常",
  "common.unknown": "未知",
  "common.countItems": "{count} 个",
  "theme.system": "跟随系统",
  "theme.light": "明亮",
  "theme.dark": "黑暗",
  "theme.lightMode": "明亮模式",
  "theme.darkMode": "黑暗模式",
  "language.system": "跟随系统",
  "language.zhCN": "中文",
  "language.enUS": "English",
  "appearance.themeModeLabel": "外观切换",
  "appearance.configureLabel": "配置外观",
  "appearance.themeColor": "颜色1",
  "appearance.accentColor": "颜色2",
  "sort.parent": "排序",
  "sort.field.name": "按名称",
  "sort.field.modifiedAt": "按时间",
  "sort.direction.asc": "升序",
  "sort.direction.desc": "降序",
  "filter.allFiles": "全部文件",
  "filter.recognized": "已识别",
  "filter.unrecognized": "未识别",
  "filter.fileFormat": "文件格式",
  "filter.allDirectories": "所有目录",
  "filter.addedDirectories": "已添加",
  "filter.allAddedDirectories": "所有已添加目录",
  "search.expandCapsule": "展开搜索胶囊",
  "search.inputLabel": "搜索关键词",
  "search.action": "搜索",
  "search.directorySelect": "目录选择",
  "search.settings": "设置",
  "search.colorScheme": "配色方案",
  "search.hideLabelHint": "右键单击隐藏标签",
  "search.showAllLabels": "显示所有标签",
  "search.hideAllLabels": "隐藏所有标签",
  "search.filterTitle": "筛选：{status}",
  "search.searching": "正在搜索…",
  "search.resultCount": "搜索结果：{count}",
  "search.recognizedCount": "已识别文件：{count}",
  "search.allFileCount": "全部文件：{count}",
  "search.unrecognizedCount": "未识别：{count}",
  "search.parseFailureCount": "解析失败：{count}",
  "search.fileFailureCount": "文件错误：{count}",
  "search.skippedUnrecognized": "搜索结果：{count} · {skippedCount} 个未识别文件未参与内容搜索",
  "search.resultGridLabel": "搜索结果",
  "search.unrecognizedGridLabel": "未识别文件列表",
  "search.emptyResult": "没有匹配的文件",
  "search.emptyUnrecognized": "没有未识别文件",
  "search.failed": "搜索失败。",
  "search.fileMissing": "文件已不存在",
  "search.guide.search": "在此键入关键词进行搜索。",
  "search.guide.showCurrent": "搜索框留空并按下回车键，可浏览当前范围内的内容。",
  "search.guide.activateCapsule": "按下 {shortcut}，随时唤起快速搜索。",
  "search.guide.activateMicro": "按下 {shortcut}，切换至 micro 模式。",
  "search.guide.activateMini": "按下 {shortcut}，切换至 mini 模式。",
  "search.guide.activateNormal": "按下 {shortcut}，使用 normal 模式浏览大量文件。",
  "search.guide.activateLine": "按下 {shortcut}，将窗口收起为 line。",
  "search.guide.openSettings": "按下 {shortcut}，快速打开设置界面。",
  "search.guide.preview": "选中一个搜索结果，按下空格键即可快速预览。",
  "search.guide.previewNavigate": "快速预览时，可使用鼠标滚轮或方向键切换文件。",
  "search.guide.previewContextMenu": "快速预览窗口也支持右键菜单。",
  "search.guide.multiSelect": "按住 Ctrl 或 Shift 点击缩略图，可以选择多个文件。",
  "search.guide.batchActions": "选择多个文件后，可以批量修改关键词或删除文件。",
  "search.guide.dragResult": "搜索结果可以直接拖至其他应用。",
  "search.guide.labels": "点击顶部标签，可以切换目录、状态、排序或文件格式。",
  "search.guide.hideLabel": "右键单击顶部标签，可以隐藏对应标签。",
  "search.guide.labelMenu": "右键单击搜索区域，可以统一隐藏或显示标签。",
  "search.guide.commandDark": "键入 ui:dark 并按下回车键，可切换至黑暗模式。",
  "search.guide.viewCommands": "在设置页中可以查看所有快捷指令。",
  "search.guide.editShortcuts": "在设置页中可以修改快捷动作。",
  "search.guide.trayNormal": "双击系统托盘图标，可以快速打开 normal 模式。",
  "search.guide.focusSearch": "按下 Ctrl+`，可以快速将焦点移回搜索框。",
  "search.guide.resultContextMenu": "右键单击搜索结果，可以查看更多文件操作。",
  "window.minimize": "最小化",
  "window.maximize": "最大化窗口",
  "window.restore": "还原窗口",
  "window.close": "关闭",
  "window.changeMode": "切换窗口模式",
  "window.collapse": "收缩",
  "window.pinToggle": "置顶/取消置顶",
  "window.openSettings": "打开设置",
  "window.returnSearch": "返回搜索页",
  "preview.close": "关闭预览",
  "preview.restore": "还原预览窗口",
  "preview.maximize": "最大化预览窗口",
  "preview.pin": "置顶",
  "preview.unpin": "取消置顶",
  "preview.loading": "正在加载预览…",
  "preview.action": "预览",
  "context.open": "打开",
  "context.showInFolder": "打开路径",
  "context.editKeywords": "编辑关键词",
  "context.deleteFile": "删除文件",
  "context.deleteSelectedFiles": "删除选中的 {count} 个文件",
  "settings.recognitionStatus": "识别状态",
  "settings.directoryConfig": "配置目录",
  "settings.directoryLoading": "正在读取目录…",
  "settings.directoryEmpty": "尚未添加目录",
  "settings.directoryCount": "{count} 个目录",
  "settings.addDirectory": "添加目录",
  "directoryAdd.added": "已添加 {count} 个目录",
  "directoryAdd.summary": "已添加 {added} 个目录，忽略 {ignored} 项，失败 {failed} 项",
  "directoryAdd.driveRootIgnored": "磁盘根目录暂不允许添加",
  "directoryAdd.alreadyAdded": "该目录已添加",
  "directoryAdd.coveredByExisting": "该目录已被“{name}”包含",
  "directoryAdd.noChanges": "没有需要添加的目录",
  "directoryAdd.failed": "添加目录失败：{path}",
  "directoryAdd.replaceDialogTitle": "合并目录范围",
  "directoryAdd.replaceQuestion": "添加 {candidates} 个所选目录将替换 {count} 个已添加的子目录，是否继续？",
  "skim.name": "轻阅",
  "skim.open": "打开轻阅",
  "skim.exit": "退出轻阅",
  "skim.computer": "此电脑",
  "skim.loading": "正在读取当前位置…",
  "skim.empty": "当前位置没有可显示的文件夹或视觉文件",
  "skim.entryCount": "{count} 个项目",
  "skim.searchElsewhere": "在轻阅中查找",
  "skim.feedbackLabel": "轻阅状态",
  "skim.invalidRequest": "轻阅读取请求无效。",
  "skim.accessDenied": "没有权限读取该目录。",
  "skim.directoryUnavailable": "目录不存在或当前不可用。",
  "skim.readFailed": "读取目录失败。",
  "settings.index": "索引",
  "settings.cancellingRecognition": "正在取消",
  "settings.continueRecognition": "继续识别",
  "settings.updateAll": "全部更新",
  "settings.recognizing": "识别中",
  "settings.scanning": "扫描中",
  "settings.indexStatus": "索引状态",
  "settings.indexStage": "当前阶段",
  "settings.indexProgress": "当前进度",
  "settings.indexSuccessCount": "成功数量",
  "settings.indexFailureCount": "失败数量",
  "settings.indexCurrentFile": "当前文件",
  "settings.indexErrorSummary": "错误摘要",
  "settings.renameDirectoryHint": "双击重命名",
  "settings.recognizeDirectory": "识别",
  "settings.recognizeDirectoryHint": "仅识别该目录",
  "settings.deleteDirectoryHint": "删除目录",
  "settings.clearCache": "清理缓存",
  "settings.cacheManagement": "缓存管理",
  "settings.readingCache": "读取中",
  "settings.cacheStats": "{count} 个 / {size}",
  "settings.cacheOptimizationReady": "{count}个 / {size}　自动优化已开启。",
  "settings.cacheOptimizationRunning": "{count}个 / {size}　正在自动优化缓存，如遇电脑卡顿可手动关闭。",
  "settings.cacheOptimizationCompleted": "{count}个 / {size}　自动优化已完成。",
  "settings.cacheOptimizationDisabled": "{count}个 / {size}　自动优化已关闭，开启可提升浏览体验。",
  "settings.cacheOptimizationOn": "自动优化",
  "settings.cacheOptimizationOff": "无优化",
  "settings.cacheOptimizationOnHint": "已开启自动生成缓存",
  "settings.cacheOptimizationOffHint": "开启后自动生成缓存",
  "settings.clearingCache": "清理中",
  "settings.clearAllCache": "清理全部",
  "settings.cacheCleared": "清理完成",
  "settings.language": "语言",
  "settings.languageSystem": "跟随系统",
  "settings.editColorHint": "单击修改",
  "settings.editShortcutHint": "单击修改",
  "settings.standbyLine": "line",
  "settings.visible": "显示",
  "settings.hidden": "不显示",
  "settings.edgeSnap": "边缘吸附",
  "settings.enabled": "打开",
  "settings.disabled": "关闭",
  "settings.launchAtLogin": "开机运行",
  "settings.launchAtLoginOn": "启动",
  "settings.launchAtLoginOff": "关闭",
  "settings.operationHints": "操作提示",
  "settings.operationHintsOn": "显示",
  "settings.operationHintsOff": "关闭",
  "settings.quickActions": "快捷动作",
  "settings.finishConfiguration": "完成配置",
  "settings.configure": "配置",
  "settings.shortcutUnavailable": "当前设置不可用，需重新设置",
  "settings.captureShortcut": "按下快捷键",
  "settings.quickCommands": "快捷指令",
  "settings.closeQuickCommands": "关闭查看",
  "settings.confirmationCommands": "需二次确认",
  "settings.confirmationCommandHint": "执行前将在输入框内要求输入 y / n 二次确认。",
  "settings.selectRuntime": "选择 llama.cpp 版本",
  "settings.selectVersion": "选择版本",
  "settings.refreshRuntime": "刷新 llama.cpp 版本",
  "settings.startServer": "启动 llama-server",
  "settings.stopServer": "停止 llama-server",
  "settings.visionModel": "视觉模型",
  "settings.selectVisionModel": "选择视觉模型",
  "settings.refreshGguf": "刷新 GGUF 模型",
  "settings.details": "详细信息 >",
  "settings.viewReleases": "查看版本发布",
  "settings.runtimeFileStatus": "运行时文件状态",
  "settings.runtimeDirectory": "运行时目录",
  "settings.serviceAddress": "服务地址",
  "settings.processPid": "进程 PID",
  "settings.runtimeStartedAt": "启动时间",
  "settings.runtimeLog": "运行日志",
  "settings.modelDirectory": "模型目录",
  "settings.modelPath": "模型路径",
  "settings.mmprojFile": "mmproj 文件",
  "settings.mainModelInfo": "主模型大小 / 修改时间",
  "settings.mmprojInfo": "mmproj 大小 / 修改时间",
  "settings.modelInventory": "可用模型 / GGUF 文件",
  "settings.viewAllSupportedHint": "双击查看全部受支持文件",
  "settings.viewRecognizedHint": "双击查看已识别文件",
  "settings.viewUnrecognizedHint": "双击查看未识别文件",
  "settings.indexScanning": "正在扫描",
  "settings.indexRecognizing": "正在识别",
  "settings.recognitionFailed": "识别失败",
  "settings.scanFailed": "扫描失败",
  "runtime.rootMissing": "目录缺失",
  "runtime.noneFound": "未发现可用版本",
  "runtime.selectionMissing": "所选版本缺失",
  "runtime.startFailed": "启动失败",
  "runtime.notFound": "未找到 llama.cpp",
  "model.unpaired": "未配对",
  "model.paired": "已配对",
  "model.selectionMissing": "所选模型缺失",
  "model.directoryMissing": "模型目录缺失",
  "model.notFound": "未找到模型",
  "shortcut.activateCapsule": "激活 capsule",
  "shortcut.activateMicro": "激活 micro",
  "shortcut.activateMini": "激活 mini",
  "shortcut.activateNormal": "激活 normal",
  "shortcut.activateLine": "激活 line",
  "shortcut.openSettings": "打开设置",
  "keywords.selectedCount": "已选择 {count} 个文件",
  "keywords.label": "关键词",
  "keywords.placeholder": "为所选项添加关键词，用逗号分隔",
  "keywords.resultTitle": "关键词更新结果",
  "keywords.updateFailedCount": "{count} 个文件更新失败。",
  "keywords.updateCompleted": "关键词更新完成。",
  "delete.fileDialogTitle": "删除文件",
  "delete.movingToTrash": "正在将 {count} 个文件移入回收站…",
  "delete.failedCount": "{count} 个文件删除失败。",
  "delete.completed": "文件删除完成。",
  "delete.fileQuestion": "是否将选中的文件移入回收站？",
  "delete.directoryDialogTitle": "删除目录",
  "delete.directoryQuestion": "是否删除目录及索引？",
  "cache.dialogTitle": "清理缓存",
  "cache.completed": "缓存清理完成。",
  "cache.regenerationHint": "视觉缓存会按需重新生成。",
  "cache.clearQuestion": "本次是否清理？",
  "commands.group.settings": "设置页",
  "commands.group.view": "查看",
  "commands.group.window": "窗口模式",
  "commands.group.tags": "标签",
  "commands.group.index": "索引",
  "commands.group.directory": "目录",
  "commands.group.appearance": "外观",
  "commands.group.appBehavior": "软件行为",
  "commands.group.line": "line",
  "commands.group.edgeSnap": "边缘吸附",
  "commands.group.shortcuts": "快捷动作",
  "commands.group.commands": "快捷指令",
  "commands.group.language": "语言",
  "commands.group.runtime": "llama.cpp",
  "commands.group.model": "视觉模型",
  "commands.group.cache": "缓存",
  "commands.set.open": "打开设置",
  "commands.set.quick": "快捷动作配置",
  "commands.set.commands": "查看快捷指令",
  "commands.example.viewDirectory": "see:dir \"目录名称\"",
  "commands.example.selectDirectory": "tag:dir \"目录名称\"",
  "commands.example.indexDirectory": "idx:dir \"目录名称\"",
  "commands.example.addDirectory": "dir:add \"完整路径\"",
  "commands.example.renameDirectory": "dir:rename \"旧\" \"新\"",
  "commands.example.selectRuntime": "llama:use \"版本名称\"",
  "commands.example.selectModel": "model:use \"模型名称\"",
  "commands.example.deleteDirectory": "dir:delete \"目录名称\"",
  "commands.view.all": "查看全部已添加文件",
  "commands.view.recognized": "查看已识别文件",
  "commands.view.unrecognized": "查看未识别文件",
  "commands.view.directory": "查看指定目录",
  "commands.window.line": "切换为 line 模式",
  "commands.window.capsule": "切换为 capsule 模式",
  "commands.window.micro": "切换为 micro 模式",
  "commands.window.mini": "切换为 mini 模式",
  "commands.window.normal": "切换为 normal 模式",
  "commands.window.max": "窗口最大化",
  "commands.window.pin": "窗口置顶",
  "commands.window.unpin": "取消窗口置顶",
  "commands.tags.showDirectory": "显示目录标签",
  "commands.tags.selectDirectory": "选择指定目录标签",
  "commands.tags.showSort": "显示排序标签",
  "commands.tags.sortAsc": "切换为升序排序",
  "commands.tags.sortDesc": "切换为降序排序",
  "commands.tags.showAll": "显示所有标签",
  "commands.tags.hideAll": "隐藏所有标签",
  "commands.tags.hideDirectory": "隐藏目录标签",
  "commands.tags.hideSort": "隐藏排序标签",
  "commands.index.all": "更新全部索引",
  "commands.index.directory": "识别指定目录",
  "commands.index.continue": "继续识别未完成文件",
  "commands.index.stop": "停止当前识别任务",
  "commands.directory.add": "添加目录",
  "commands.directory.rename": "重命名目录显示名",
  "commands.directory.refresh": "刷新目录统计 / 状态",
  "commands.appearance.light": "切换明亮模式",
  "commands.appearance.dark": "切换黑暗模式",
  "commands.appearance.system": "跟随系统主题",
  "commands.appearance.themeColor": "设置颜色1",
  "commands.appearance.accentColor": "设置颜色2",
  "commands.appearance.reset": "恢复默认外观配置",
  "commands.app.startupEnable": "开启开机运行",
  "commands.app.startupDisable": "关闭开机运行",
  "commands.app.hintsEnable": "显示操作提示",
  "commands.app.hintsDisable": "关闭操作提示",
  "commands.line.show": "显示 line",
  "commands.line.hide": "隐藏 line",
  "commands.edgeSnap.enable": "开启边缘吸附",
  "commands.edgeSnap.disable": "关闭边缘吸附",
  "commands.shortcuts.enable": "启用全局快捷键",
  "commands.shortcuts.disable": "禁用全局快捷键",
  "commands.shortcuts.reset": "恢复快捷动作默认配置",
  "commands.parser.enable": "启用快捷指令解析",
  "commands.parser.disable": "禁用快捷指令解析",
  "commands.language.system": "跟随系统语言",
  "commands.language.chinese": "中文界面",
  "commands.language.english": "英文界面",
  "commands.runtime.start": "启动 llama.cpp / llama-server",
  "commands.runtime.select": "切换 llama.cpp 版本",
  "commands.runtime.refresh": "刷新 llama.cpp 版本列表",
  "commands.model.refresh": "刷新视觉模型列表",
  "commands.model.select": "切换视觉模型",
  "commands.cache.thumbnail": "仅清理缩略图缓存",
  "commands.cache.preview": "仅清理预览缓存",
  "commands.cache.model": "仅清理模型输入图缓存",
  "commands.confirm.deleteDirectory": "删除目录、索引和相关缓存",
  "commands.confirm.clearIndex": "清除全部索引",
  "commands.confirm.quit": "关闭 Cap7CE 运行进程",
  "commands.confirm.stopRuntime": "停止 llama.cpp / llama-server",
  "commands.confirm.clearCache": "清理缩略图 / 预览 / 模型输入缓存",
  "command.pending": "暂不支持：{command}",
  "command.invalid": "指令无效：{command}",
  "command.missingArgument": "缺少参数：{message}",
  "command.missingArgumentGeneric": "缺少参数",
  "command.missingDirectoryName": "缺少目录名称",
  "command.missingDirectoryPath": "缺少目录路径",
  "command.missingColor": "缺少颜色值",
  "command.missingRuntimeName": "缺少 llama.cpp 版本名称",
  "command.missingModelName": "缺少模型名称",
  "command.enterYesOrNo": "请输入 y 或 n",
  "command.cancelled": "已取消操作",
  "command.taskRunning": "已有任务正在运行",
  "command.taskNotRunning": "当前没有正在运行的任务",
  "command.directoryNotFound": "未找到目录",
  "command.directoryNameEmpty": "目录名称不能为空",
  "command.viewedAll": "已查看全部文件",
  "command.viewedRecognized": "已查看已识别文件",
  "command.viewedUnrecognized": "已查看未识别文件",
  "command.viewedDirectory": "已查看目录：{name}",
  "command.windowChanged": "已切换为 {mode} 模式",
  "command.windowMaximized": "已最大化窗口",
  "command.windowPinEnabled": "已开启窗口置顶",
  "command.windowPinDisabled": "已关闭窗口置顶",
  "command.directoryLabelShown": "已显示目录标签",
  "command.directorySelected": "已选择目录：{name}",
  "command.sortLabelShown": "已显示排序标签",
  "command.sortAsc": "已切换升序排序",
  "command.sortDesc": "已切换降序排序",
  "command.allLabelsShown": "已显示所有标签",
  "command.allLabelsHidden": "已隐藏所有标签",
  "command.directoryLabelHidden": "已隐藏目录标签",
  "command.sortLabelHidden": "已隐藏排序标签",
  "command.indexAllStarted": "已开始更新全部索引",
  "command.directoryRecognitionStarted": "已开始识别目录：{name}",
  "command.recognitionContinued": "已继续识别未完成文件",
  "command.recognitionStopped": "已停止当前识别任务",
  "command.confirmDeleteDirectory": "确认删除目录“{name}”？输入 y / n",
  "command.directoryDeleted": "已删除目录：{name}",
  "command.directoryDeleteFailed": "删除目录失败",
  "command.directoryRenamed": "已重命名目录：{name}",
  "command.directoryStatusRefreshed": "已刷新目录状态",
  "command.settingsOpened": "已打开设置",
  "command.quickActionsOpened": "已打开快捷动作配置",
  "command.quickCommandsOpened": "已打开快捷指令",
  "command.themeChanged": "已切换{theme}",
  "command.invalidColor": "颜色值无效",
  "command.themeColorSet": "已设置颜色1",
  "command.accentColorSet": "已设置颜色2",
  "command.appearanceReset": "已恢复默认外观配置",
  "command.lineShown": "已显示 line",
  "command.lineHidden": "已隐藏 line",
  "command.edgeSnapEnabled": "已开启边缘吸附",
  "command.edgeSnapDisabled": "已关闭边缘吸附",
  "command.globalShortcutsEnabled": "已开启全局快捷键",
  "command.globalShortcutsDisabled": "已关闭全局快捷键",
  "command.globalShortcutsFailed": "全局快捷键注册失败",
  "command.shortcutsReset": "已恢复快捷动作默认配置",
  "command.defaultShortcutsUnavailable": "默认快捷键当前不可用",
  "command.parserEnabled": "已启用快捷指令解析",
  "command.parserDisabled": "已禁用快捷指令解析",
  "command.launchAtLoginEnabled": "已开启开机运行",
  "command.launchAtLoginDisabled": "已关闭开机运行",
  "command.operationHintsEnabled": "已显示操作提示",
  "command.operationHintsDisabled": "已关闭操作提示",
  "command.languageSystem": "已切换为跟随系统语言",
  "command.languageChinese": "已切换为中文",
  "command.languageEnglish": "已切换为 English",
  "command.runtimeListRefreshed": "已刷新 llama.cpp 版本列表",
  "command.runtimeStarted": "已启动 llama.cpp",
  "command.runtimeSelected": "已切换 llama.cpp 版本：{name}",
  "command.confirmStopRuntime": "确认停止 llama.cpp？输入 y / n",
  "command.runtimeStopped": "已停止 llama.cpp",
  "command.runtimeStopFailed": "停止 llama.cpp 失败",
  "command.modelListRefreshed": "已刷新视觉模型列表",
  "command.modelSelected": "已切换视觉模型：{name}",
  "command.confirmClearCache": "确认清理缓存？输入 y / n",
  "command.cacheCleared": "已清理缓存",
  "command.cacheClearFailed": "清理缓存失败",
  "command.confirmQuit": "确认退出 Cap7CE？输入 y / n",
  "command.quitting": "正在退出 Cap7CE",
  "command.quitFailed": "退出 Cap7CE 失败",
  "error.connectionFailed": "连接失败",
  "error.scanUnavailable": "扫描服务暂时不可用。",
  "error.scanFailed": "扫描失败。",
  "error.recognitionFailed": "AI 识别失败。",
  "error.supplementUnavailable": "补识别服务暂时不可用。",
  "error.supplementFailed": "补识别失败。",
  "error.indexUnavailable": "文件索引服务暂时不可用。",
  "error.batchKeywordFailed": "关键词批量更新失败。",
  "error.metadataSaveFailed": "保存描述和关键词失败。",
  "error.fileOperationUnavailable": "文件操作服务暂时不可用。",
  "error.fileDeletedRefreshFailed": "文件已删除，但状态刷新失败，正在重新加载。",
  "error.partialDeleteFailed": "部分文件删除失败。",
  "error.deleteIncomplete": "文件删除未完成。",
  "error.deleteFailed": "删除文件失败。",
  "error.cacheUnavailable": "缓存清理服务暂时不可用。",
  "error.cacheFailed": "缓存清理失败。",
  "error.directoryStatusRefreshFailed": "刷新目录状态失败",
  "error.runtimeRefreshFailed": "刷新 llama.cpp 版本列表失败",
  "error.runtimeAlreadyRunning": "llama.cpp 已在运行",
  "error.runtimeStartFailed": "llama.cpp 启动失败",
  "error.stopRecognitionFirst": "请先停止当前识别任务",
  "error.runtimeVersionNotFound": "未找到 llama.cpp 版本",
  "error.runtimeSwitchFailed": "切换 llama.cpp 版本失败",
  "error.modelRefreshFailed": "刷新视觉模型列表失败",
  "error.modelNotFound": "未找到视觉模型",
  "error.modelSwitchFailed": "切换视觉模型失败",
  "error.directoryRenameFailed": "重命名目录失败",
  "error.windowPinEnableFailed": "开启窗口置顶失败",
  "error.windowPinDisableFailed": "关闭窗口置顶失败",
  "error.runtimeNotRunning": "llama.cpp 未运行",
  "error.runtimeStopFailed": "停止 llama.cpp 失败",
  "error.quitFailed": "退出 Cap7CE 失败",
  "error.normalWindowSwitchFailed": "切换为 normal 模式失败",
  "error.windowMaximizeFailed": "最大化窗口失败",
  "error.windowPinUpdateFailed": "更新窗口置顶状态失败",
  "error.fileDeleteServiceFailed": "文件删除服务失败。",
  "error.fileDragStartFailed": "文件拖拽启动失败。",
  "error.directoryDoesNotExist": "指定目录不存在。",
  "error.fileOutsideAddedDirectories": "文件不属于已添加目录。",
  "error.fileMissingOrStale": "文件不存在或已失效。",
  "error.invalidFile": "文件无效。",
  "error.invalidMetadata": "描述或关键词格式无效。",
  "error.invalidBatchKeywordSource": "关键词批量更新请求来源无效。",
  "error.noBatchKeywordSelection": "未选择需要更新的文件。",
  "error.invalidBatchKeywordParameters": "关键词批量更新参数无效。",
  "error.invalidBatchKeywordTarget": "关键词批量更新目标无效。",
  "error.unsupportedFile": "不支持的文件：{path}",
  "error.duplicateBatchKeywordTarget": "关键词批量更新目标重复。",
  "error.stopServerBeforeRuntimeSwitch": "请先停止 llama-server，再切换 llama.cpp 版本。",
  "error.stopServerBeforeModelSwitch": "请先停止 llama-server，再切换视觉模型。",
  "error.cacheConfirmationRequired": "清理缓存需要用户确认。",
  "scan.directoryInvalid": "目录不存在或不是文件夹",
  "scan.directoryUnavailable": "目录不存在或无法访问",
  "scan.skippedDirectories": "有 {count} 个子目录无法读取",
  "file.sourceMissing": "源文件不存在。",
  "file.trashPermissionDenied": "没有权限将文件移动到回收站。",
  "file.trashOperationAborted": "系统回收站操作被中止，重试后仍失败。文件可能仍被其他程序占用。",
  "file.trashFailedWithMessage": "移动到回收站失败：{message}",
  "file.trashFailed": "移动到回收站失败。",
  "file.sourceNotFile": "源路径不是文件。",
  "file.protectedCache": "拒绝删除 Cap7CE 自身缓存文件。",
  "file.outsideAddedDirectories": "文件不属于当前已添加目录。",
  "recognition.pending": "未识别",
  "recognition.fileError": "文件错误",
  "recognition.parseFailed": "解析失败",
  "runtime.rootNotFound": "未找到 llama.cpp 目录：{path}",
  "runtime.serverNotFound": "未检测到包含 llama-server.exe 的版本目录。",
  "runtime.selectVersion": "请选择一个 llama.cpp 版本。",
  "runtime.selectedVersionMissing": "已选择的版本 {name} 不存在，请重新选择。",
  "runtime.versionUnavailable": "llama.cpp 版本不可用：{name}",
  "runtime.healthCheckFailed": "llama-server 连续健康检查失败，进程已停止。",
  "runtime.selectAvailable": "请先选择可用的 llama.cpp 版本。",
  "runtime.cancelled": "llama-server 启动已取消。",
  "runtime.loadingModel": "正在加载主模型和 mmproj。",
  "runtime.waitingForHealth": "正在加载视觉模型并等待健康检查。",
  "runtime.unexpectedExit": "llama-server 意外退出（退出码 {code}）。",
  "runtime.unexpectedExitWithDetail": "llama-server 意外退出（退出码 {code}）：{detail}",
  "runtime.startupExit": "llama-server 启动期间退出（退出码 {code}）。",
  "runtime.startupExitWithDetail": "llama-server 启动期间退出（退出码 {code}）：{detail}",
  "runtime.modelNotReported": "健康检查已通过，但模型列表中未发现所选模型。",
  "runtime.modelLoaded": "视觉模型和 mmproj 已加载。",
  "runtime.healthCheckPassed": "健康检查通过。",
  "runtime.healthCheckTimeout": "llama-server 在 {seconds} 秒内未通过健康检查。",
  "runtime.noAvailablePort": "无法找到可用的本地端口，llama-server 未启动。",
  "runtime.modelSelectedNotLoaded": "模型已选择，尚未加载。",
  "runtime.modelUnselected": "尚未选择视觉模型。",
  "runtime.serverStopped": "llama-server 已停止。",
  "model.configurationUnavailable": "视觉模型配置不可用。",
  "model.mmprojNotFound": "未找到可明确匹配的 mmproj GGUF 文件。",
  "model.rootNotFound": "未找到 models 目录：{path}",
  "model.select": "请选择视觉模型。",
  "model.mainModelNotFound": "未检测到主模型 GGUF 文件。",
  "model.selectedMissing": "已选择的视觉模型不存在，请刷新后重新选择。",
  "model.notExists": "视觉模型不存在：{name}",
  "model.mmprojMissing": "所选视觉模型缺少 mmproj 文件。",
  "recognition.cancelled": "AI 识别已取消",
  "recognition.readingPending": "正在读取待识别文件",
  "recognition.noPending": "没有待识别文件",
  "recognition.startingRuntime": "正在启动 llama.cpp 并检查视觉模型",
  "recognition.processing": "正在识别第 {current} / {total} 个文件",
  "recognition.failed": "识别失败",
  "recognition.progressSummary": "已完成 {completed}，失败 {failed}",
  "recognition.completedSummary": "AI 识别完成：成功 {completed}，失败 {failed}",
  "dialog.selectIndexDirectory": "选择索引目录",
  "tray.hideLine": "隐藏 line",
  "tray.showLine": "显示 line",
  "tray.disableEdgeSnap": "关闭边缘吸附",
  "tray.enableEdgeSnap": "打开边缘吸附",
  "tray.openSettings": "打开设置",
  "tray.quit": "退出 Cap7CE"
} as const;

export type TranslationKey = keyof typeof zhCN;
export type ChineseLocale = typeof zhCN;
export type TranslationParameters = Record<string, string | number>;
export type LanguagePreference = "system" | "zh-CN" | "en-US";
export type ResolvedLanguage = Exclude<LanguagePreference, "system">;

const locales: Record<ResolvedLanguage, Record<TranslationKey, string>> = {
  "zh-CN": zhCN,
  "en-US": enUS
};

let activeLanguage: ResolvedLanguage = "zh-CN";

export const resolveLanguagePreference = (
  preference: LanguagePreference,
  systemLanguage: string
): ResolvedLanguage => preference === "system"
  ? systemLanguage.toLowerCase().startsWith("zh") ? "zh-CN" : "en-US"
  : preference;

export const setActiveLanguage = (language: ResolvedLanguage) => {
  activeLanguage = language;
};

export const getActiveLanguage = () => activeLanguage;

export const t = (key: TranslationKey, parameters: TranslationParameters = {}): string => {
  const template = locales[activeLanguage][key] ?? zhCN[key];
  return template.replace(/\{([^}]+)\}/g, (placeholder, name: string) => (
    Object.prototype.hasOwnProperty.call(parameters, name) ? String(parameters[name]) : placeholder
  ));
};
